sudo: required
dist: trusty
language: java
services: docker

before_script:
    - export IMAGE="raleng/zomdie:kotlin"
    - docker pull ${IMAGE}

script:
    - make debug

notifications:
  email:
    on_success: change
    on_failure: change
