sudo: required
dist: trusty
language: generic
services: docker

before_script:
    - export IMAGE="raleng/zomdie:latest"
    - docker pull ${IMAGE}

script:
    - make release

notifications:
  email:
    on_success: change
    on_failure: change
